name: Java Calculator Workflow

on:
  push:  # Runs on every push
  workflow_dispatch:  # Allows manual trigger

jobs:
  build_and_run:
    runs-on: ubuntu-latest  # Runs on a Linux virtual machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetches repo code

      # - name: Set up Java
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '17'
      #     distribution: 'temurin'  # Use Java 17 (change if needed)

      # - name: Compile Java Code
      #   run: javac Calculator.java  # Compiles the Java program

      # - name: Run Calculator
      #   run: java Calculator  # Runs the Java program
