name: Java Calculator Workflow

on:
  push:  # Runs on every push
  workflow_dispatch:  # Allows manual trigger

jobs:
  build_and_run:
    runs-on: windows-latest


    steps:
      - run: echo"hi iam in linux" 
    # Runs on a Linux virtual machine

    # steps:
    #   - name: Checkout Repository
    #     uses: actions/checkout@v3  # Fetches repo code

    #   - name: Set up Java
    #     uses: actions/setup-java@v3
    #     with:
    #       java-version: '17'
    #       distribution: 'temurin'  # Use Java 17 (change if needed)
  builds-linux:
    runs-on: ubuntu-latest

    steps:
      - run: echo"hi iam in linux" 
      # - name: Compile Java Code
      #   run: javac src/Calculator.java  
      #   # Compiles the Java program
      # - name: Debug - List Files
      #   run: ls -R  # Lists all files in the repository
  

      # - name: Run Calculator
      #   run: java src.Calculator  
      # - name: Compile Java Code
      #   run: javac -d bin src/Calculator.java  # Compile into bin/

      # - name: Run Calculator
      #   run: java -cp bin src.Calculator  # Use full package name
# Runs the Java program
